
[34m[1mwandb[39m[22m: Downloading large artifact bert-tiny-eecq0ads:latest, 341.32MB. 1 files... Done. 0:0:0
Loading features from: ../nets/temp/epoch_10.cp
parameters loaded on feature net
--------------------Reading error -------------------
--------------------Reading error -------------------
data split [25.4 %, 3.1 %, 3.1 %], 68.5 % discarded as buffer
--------------------Reading error -------------------
--------------------Reading error -------------------
data split [25.2 %, 3.1 %, 3.1 %], 68.6 % discarded as buffer
-----------------------------3------------IN AAA------------
---------------------------------
torch.Size([23, 256, 1])
---------------------------------
----------------Gen-----------------
tensor([[[ 0.4912],
         [ 0.3609],
         [-0.4677],
         ...,
         [ 0.5516],
         [ 0.5469],
         [ 0.0421]],
        [[ 0.5484],
         [-0.6133],
         [ 0.1511],
         ...,
         [-0.7564],
         [-0.7528],
         [-0.6857]],
        [[ 0.0229],
         [ 0.3825],
         [-0.4128],
         ...,
         [-0.3041],
         [ 0.5073],
         [ 0.7397]],
        ...,
        [[ 0.2518],
         [-0.6729],
         [-0.5229],
         ...,
         [-0.2257],
         [ 0.4546],
         [ 0.1590]],
        [[ 0.5279],
         [ 0.2988],
         [-0.0453],
         ...,
         [ 0.4870],
         [-0.3569],
         [ 0.1094]],
        [[ 0.0102],
         [-0.7964],
         [ 0.5367],
         ...,
         [ 0.8087],
         [ 0.8716],
         [ 0.1142]]])
torch.Size([23, 256, 1])
----------------Gen-----------------
Traceback (most recent call last):
  File "/Users/ayushshekhar/Desktop/work/ml/Master/src/main.py", line 129, in <module>
    plot_one(copy_update(idea, st_lr_decay=1, st_lr=0.001, num_iters=100, **TEST), name="base")
  File "/Users/ayushshekhar/Desktop/work/ml/Master/src/plot.py", line 183, in plot_one
    fig.savefig('svg/ex_%s.svg' % name, format='svg')
  File "/Users/ayushshekhar/anaconda3/envs/py3.9/lib/python3.9/site-packages/matplotlib/figure.py", line 3046, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/Users/ayushshekhar/anaconda3/envs/py3.9/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 2319, in print_figure
    result = print_method(
  File "/Users/ayushshekhar/anaconda3/envs/py3.9/lib/python3.9/site-packages/matplotlib/backend_bases.py", line 1648, in wrapper
    return func(*args, **kwargs)
  File "/Users/ayushshekhar/anaconda3/envs/py3.9/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 389, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/Users/ayushshekhar/anaconda3/envs/py3.9/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 415, in wrapper
    return func(*inner_args, **inner_kwargs)
  File "/Users/ayushshekhar/anaconda3/envs/py3.9/lib/python3.9/site-packages/matplotlib/backends/backend_svg.py", line 1321, in print_svg
    with cbook.open_file_cm(filename, "w", encoding="utf-8") as fh:
  File "/Users/ayushshekhar/anaconda3/envs/py3.9/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 465, in open_file_cm
    fh, opened = to_filehandle(path_or_file, mode, True, encoding)
  File "/Users/ayushshekhar/anaconda3/envs/py3.9/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 451, in to_filehandle
    fh = open(fname, flag, encoding=encoding)
FileNotFoundError: [Errno 2] No such file or directory: 'svg/ex_base.svg'