2024-04-05 22:02:02,665 INFO    MainThread:52881 [wandb_setup.py:_flush():76] Loading settings from /Users/ayushshekhar/.config/wandb/settings
2024-04-05 22:02:02,665 INFO    MainThread:52881 [wandb_setup.py:_flush():76] Loading settings from /Users/ayushshekhar/Desktop/work/ml/Master/src/wandb/settings
2024-04-05 22:02:02,665 INFO    MainThread:52881 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-04-05 22:02:02,665 INFO    MainThread:52881 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'src/main.py', 'program': '/Users/ayushshekhar/Desktop/work/ml/Master/src/main.py'}
2024-04-05 22:02:02,666 INFO    MainThread:52881 [wandb_init.py:_log_setup():428] Logging user logs to /Users/ayushshekhar/Desktop/work/ml/Master/src/wandb/run-20240405_220202-1d98q13f/logs/debug.log
2024-04-05 22:02:02,666 INFO    MainThread:52881 [wandb_init.py:_log_setup():429] Logging internal logs to /Users/ayushshekhar/Desktop/work/ml/Master/src/wandb/run-20240405_220202-1d98q13f/logs/debug-internal.log
2024-04-05 22:02:02,666 INFO    MainThread:52881 [wandb_init.py:init():462] calling init triggers
2024-04-05 22:02:02,666 INFO    MainThread:52881 [wandb_init.py:init():465] wandb.init called with sweep_config: {}
config: {}
2024-04-05 22:02:02,666 INFO    MainThread:52881 [wandb_init.py:init():515] starting backend
2024-04-05 22:02:02,666 INFO    MainThread:52881 [backend.py:_multiprocessing_setup():97] multiprocessing start_methods=spawn,fork,forkserver, using: spawn
2024-04-05 22:02:02,682 INFO    MainThread:52881 [backend.py:ensure_launched():217] starting backend process...
2024-04-05 22:02:02,689 INFO    MainThread:52881 [backend.py:ensure_launched():222] started backend process with pid: 52888
2024-04-05 22:02:02,690 INFO    MainThread:52881 [wandb_init.py:init():525] backend started and connected
2024-04-05 22:02:02,697 INFO    MainThread:52881 [wandb_init.py:init():596] updated telemetry
2024-04-05 22:02:02,715 INFO    MainThread:52881 [wandb_init.py:init():627] communicating run to backend with 30 second timeout
2024-04-05 22:02:32,720 INFO    MainThread:52881 [interface_shared.py:_communicate_run():326] couldn't get run from backend
2024-04-05 22:02:32,722 ERROR   MainThread:52881 [wandb_init.py:init():636] backend process timed out
2024-04-05 22:02:32,722 ERROR   MainThread:52881 [wandb_init.py:init():647] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2024-04-05 22:02:32,735 ERROR   MainThread:52881 [wandb_init.py:init():1026] error
Traceback (most recent call last):
  File "/Users/ayushshekhar/anaconda3/envs/py3.9/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 999, in init
    run = wi.init()
  File "/Users/ayushshekhar/anaconda3/envs/py3.9/lib/python3.9/site-packages/wandb/sdk/wandb_init.py", line 651, in init
    backend.cleanup()
  File "/Users/ayushshekhar/anaconda3/envs/py3.9/lib/python3.9/site-packages/wandb/sdk/backend/backend.py", line 246, in cleanup
    self.interface.join()
  File "/Users/ayushshekhar/anaconda3/envs/py3.9/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 475, in join
    super().join()
  File "/Users/ayushshekhar/anaconda3/envs/py3.9/lib/python3.9/site-packages/wandb/sdk/interface/interface.py", line 666, in join
    _ = self._communicate_shutdown()
  File "/Users/ayushshekhar/anaconda3/envs/py3.9/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 472, in _communicate_shutdown
    _ = self._communicate(record)
  File "/Users/ayushshekhar/anaconda3/envs/py3.9/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 226, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/Users/ayushshekhar/anaconda3/envs/py3.9/lib/python3.9/site-packages/wandb/sdk/interface/interface_shared.py", line 231, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
